### ISSUE TITLE
Not Getting M2M Relationship Folders

### ISSUE THREAD

**Issue by frick-brian** [amervitz/CrmDataPackager#7]
Hello
I stumbled upon your tool while looking for the best way to automate the ALM of MM relationships across many CRM orgs.  We are using Azure DevOps CICD pretty successfully using the normal config migration toolset, but of course, MM relationships never worked in that tool.

I have followed the steps, and I am doing a very simple move to just prove that it will work, and then I'll try and push this up into our ALM pipelines.  But when I do the import of the zip file that is build using the Compress-Crmdata command, the MM relationships do not exist in target environment.

So, I look at your screenshots, and look at my file structure.  I do not have the m2mrelationships folder in my extracts.   I also realize that the schema XML file I am providing has a relationship included in the entity definition.
![image](https://user-images.githubusercontent.com/15112935/230140657-8339503f-d4d2-4394-b6e6-f5db80d1d288.png)

But the data.xml file that is exported into data.zip from the normal Configuration Migration tool has a blank <m2mrelationships /> tag under taht same entity.  The data.xml file generated by the Compress-Crmdata inside of data.zip similarly has a blank <m2mrelationships /> tag.  
![image](https://user-images.githubusercontent.com/15112935/230141497-b9f419bf-7395-4cc2-935b-0a9d97fdcdd3.png)

Do I need to alter the settings.json file to ensure that I am pulling the correct entity, relationships, and fields?  Or should the schema.xml file be enough to tell the tool what I am looking for?

![image](https://user-images.githubusercontent.com/15112935/230141080-41d27c97-df3b-4217-abb0-7069dda1caed.png)

![image](https://user-images.githubusercontent.com/15112935/230141177-361ff5cc-03dc-437b-8aa1-49c577c2d6a6.png)
(No m2mrelationships folder in the entity folder)

I think there is a lot of promise for this tool - I guess if I can't get it running as is, I will try and dig through the code and see if we can make it work that way.  Migrating MM relationships _in an automated fashion_ has been a sticking point for years.  Thanks for any advice you can offer.

**Comment by amervitz** [comment]
Hi @frick-brian, This code hasn't changed in a while so I think it's unlikely there's a bug in the code, and it's likely a data issue.

I might be missing something here but it seems like the problem is the original data export zip file created with the Configuration Migration tool doesn't include the schema or data for the needed many-to-many relationships. Try taking a look at this documentation https://learn.microsoft.com/en-us/power-platform/admin/create-schema-export-configuration-data and ensure you're including these relationships under the entities when defining the schema file. Then, perform the data export afterwards, and `Expand-CrmData` should be able to extract them.

**Comment by frick-brian** [comment]
I appreciate the quick reply!

As far as I can tell, I do have the relationship added - its a self-referential MM, as shown here.  This is the only MM relationship on this table.
![image](https://user-images.githubusercontent.com/15112935/230182593-4b91a93b-9990-46c6-9991-d32b6687ee86.png)


And in the file thats generated when I save the schema, it does appear that the XML is configured to grab that relationship.
![image](https://user-images.githubusercontent.com/15112935/230182927-8da9b8f4-79a9-4c78-930e-3628f0144b7f.png)


There are 4 total records I am exporting from that table, 2 are "parents" and 2 are "Children" - both child records are associated to both parent records in the source environment.  

Another pointed question - Do I need to specify in the settings.json these entities that I am pulling MMs for?  I went through the documentation here on git about the settings.json file, and it doesn't seem to be necessary to add the additional entities I am pulling from, but wanted to be sure.

I will keep digging and hopefully be able to come to a resolution on this.  If you think of anything, ping back here and I'll certainly give it a try.  I was able to get the PS module installed in my DevOps pipeline tasks, so I think once I have the process down correctly, I should be able to transfer what I've learned up to our pipelines.  Thanks again and have a great rest of your day - hope to hear from you again soon.

**Comment by amervitz** [comment]
You don't need to specify a settings.json file when running Expand-CrmData.

Here's an example I've run through of creating a self-referential m2m relationship on the account entity and extracting the data after an export.

Created the m2m relationship:

![image](https://user-images.githubusercontent.com/10599498/230271212-fb8c2781-18c6-4e1f-967b-271a815239d8.png)

![image](https://user-images.githubusercontent.com/10599498/230272607-d9380d6b-66d4-43d1-815b-f341aad96057.png)

Created the schema file that includes the m2m relationship:

![image](https://user-images.githubusercontent.com/10599498/230271036-103ffec7-3998-467f-ab3d-5a6935ba201d.png)

Exported the records to a zip file:

![image](https://user-images.githubusercontent.com/10599498/230270921-54e107aa-fe53-49a3-ae95-e5c5d301e8da.png)

Opened the zip file, opened the data.xml file, and verified the m2m relationships are present:

![image](https://user-images.githubusercontent.com/10599498/230271630-eb82a388-ec4d-45e8-ae94-40a76e961e42.png)

Ran Expand-CrmData to unpack the records:

```PowerShell
Expand-CrmData -ZipFile .\Downloads\data.zip -Folder .\Downloads\extracted
```
Viewed the m2m relationship files exist in the extract folder:

![image](https://user-images.githubusercontent.com/10599498/230271885-5d25aac5-ecbb-4042-890f-4f9280bb90c8.png)

**Comment by frick-brian** [comment]
Thank you again for taking the time to reply.  

I found the issue - I was adding the relationship by double clicking, or clicking "add entity" when I had the 'show relationships' box checked.  Once you add the relationship as a field (Add Field), it worked perfectly!

Thank you - now I am going to try and see if I can't wire this up to my CICD pipes where we dynamically generate data pushes on a weekly basis.  This is going to be great, thanks again for your time and great work on this tool.
