### ISSUE TITLE
Cannot Insert Duplicate Key, even though no key exists

### ISSUE THREAD

**Issue by frick-brian** [amervitz/CrmDataPackager#8]
Hello - me again!  

So, my initial testing, of a simple data set, was fine when I was doing all creates of new records, and not trying to update existing records.  

So, we took our small testing example and expanded it to our entire data set - this particular client we are pushing 4100 records over 59 entities.  Out of all of those records and tables, we only have 1 MM relationship we have to push.

So, when we did the initial push using your tool, we were monitoring 1 specific parent record, which should have 6 children based on the relationship in the source environment.  But when we checked through the UI, we only had 2.

So we re-ran it, and no diference.  In the logs we see a few things of note.

First is 'association already exists' which makes sense - the record should be skipped if there is already an association between them.  So, I don't consider this an issue (I have yet to dive fully into the target environment data to ensure that _all_ MMs are present). 

3:46 PM AddM2MRelationships - Result: True - Entity: xxx_filingtype - Skipping N:N relationship associate between xxx_filingtype (ID:e39d2e35-7ef1-ea11-a813-001dd8309076) and xxx_filingtype (ID:59762501-cb9e-eb11-b1ac-001dd804a387), association already exists.

The second and more concerning one is the cannot insert duplicate key.  I'd expect this to have the same warning message (Association already exists), rather than a duplicate key message here.

AddM2MRelationships - Result: False - Entity: xxx_filingtype - Failed to Link N:N relationship associate between xxx_filingtype (ID:437b11c3-b9fb-ea11-a813-001dd8309076) and xxx_filingtype (IDs: ad5feec9-b095-ec11-8d20-001dd804d1ab,32beab16-d659-ec11-8f8e-001dd80509b8,cf76017a-524a-ed11-bba0-001dd8050a6e,4bfbf7f9-2d77-ed11-81ab-001dd806a09f,**_ce90a9fb-2e77-ed11-81ab-001dd806a09f_**,9916ccba-fab8-ed11-83fe-001dd806a09f,e6836a0a-fcb8-ed11-83fe-001dd806a09f,25bb5472-47c3-ed11-83ff-001dd806a09f,ccaa70f9-48c3-ed11-83ff-001dd806a09f,dcdb34b0-4ac3-ed11-83ff-001dd806a09f,05124791-1156-ed11-bba3-001dd806a09f,8ec6f790-1356-ed11-bba3-001dd806a09f,79e15e15-995f-ed11-9562-001dd806ab0c,8197853d-e671-ed11-9562-001dd806ab0c,fc18b536-074f-ed11-bba0-001dd806ab0c,85fd6dc5-8350-ed11-bba0-001dd806ab0c,b5c2d63b-8750-ed11-bba0-001dd806ab0c,5d5ef611-8b50-ed11-bba0-001dd806ab0c,c9e0c666-9a50-ed11-bba0-001dd806ab0c), Link Operation Failed with error : ************ FaultException`1 - Associate : Executing CreateMultiEntityAssociation |=> Cannot insert duplicate key.
Cannot insert duplicate key. => Cannot insert duplicate key. => Cannot insert duplicate key.[TerminalF

When I went into SQL4CDS to check the relationship table, for the specific parent record we were monitoring on the import process, there were no records in the relationship table that had the GUID as either record1 or record2 in that table.  The bold/underlined GUID from the error above is the one I ran this query for with no results.
![image](https://user-images.githubusercontent.com/15112935/230993193-6a85fe3e-564e-40e9-86b5-7181d2e4cb18.png)

So even when the relationship table is empty, and the UI component showing the child record is also empty, I am seemingly still getting the cannot insert duplicate key error message.  

I am thinking I've got to be missing something really simple here.  Any thoughts on your end?  Thanks for your help!

**Comment by amervitz** [comment]
Hi @frick-brian. This project only handles the functionality in the Expand-CrmData and Compress-CrmData PowerShell functions. The import issue you're describing is not performed by these functions, but by the Configuration Migration tool, which I am unable to provide support for. You should open a support case with Microsoft through your Dynamics 365 subscription if you believe there is a bug in that tool.

**Comment by frick-brian** [comment]
Thank you kindly, I figured it might be beyond your scope but couldn't hurt to ask.  Appreciate the work you've put into this tool, I am still going to try and get it running as we need MMs to be migrated!  Thanks again.
